var classes = [
    {
        "name": "DanchukAS\\DenyMultiplyRun\\DenyMultiplyRun",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPidFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "safeSetPidIntoFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pidNotActual",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPidFromFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pidIsNoEmpty",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pidIsPossible",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pidNoExisting",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPidIntoFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pidFileUpdated",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deletePidFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 10,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 11,
        "ccnMethodMax": 4,
        "externals": [
            "DanchukAS\\DenyMultiplyRun\\File",
            "DanchukAS\\DenyMultiplyRun\\File",
            "DanchukAS\\DenyMultiplyRun\\File",
            "DanchukAS\\DenyMultiplyRun\\File",
            "self",
            "DanchukAS\\DenyMultiplyRun\\File",
            "self",
            "self",
            "self",
            "self",
            "self",
            "DanchukAS\\DenyMultiplyRun\\File",
            "DanchukAS\\DenyMultiplyRun\\Exception\\ReadFileFail",
            "self",
            "self",
            "DanchukAS\\DenyMultiplyRun\\Exception\\ConvertPidFail",
            "self",
            "DanchukAS\\DenyMultiplyRun\\Exception\\PidFileEmpty",
            "DanchukAS\\DenyMultiplyRun\\Exception\\PidLessMin",
            "DanchukAS\\DenyMultiplyRun\\Exception\\PidBiggerMax",
            "DanchukAS\\DenyMultiplyRun\\Exception\\ProcessExisted",
            "RuntimeException",
            "DanchukAS\\DenyMultiplyRun\\File"
        ],
        "lcom": 12,
        "length": 172,
        "vocabulary": 51,
        "volume": 975.66,
        "difficulty": 13.07,
        "effort": 12753.23,
        "level": 0.08,
        "bugs": 0.33,
        "time": 709,
        "intelligentContent": 74.64,
        "number_operators": 50,
        "number_operands": 122,
        "number_operators_unique": 9,
        "number_operands_unique": 42,
        "cloc": 96,
        "loc": 209,
        "lloc": 113,
        "mi": 76.17,
        "mIwoC": 32.8,
        "commentWeight": 43.37,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.03,
        "relativeSystemComplexity": 5.03,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 12.33,
        "totalSystemComplexity": 60.33,
        "pageRank": 0.05,
        "afferentCoupling": 0,
        "efferentCoupling": 23,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\File",
        "interface": false,
        "methods": [
            {
                "name": "lockPidFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "safeCloseFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unlockFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "closeFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "closeFileFailed",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "openFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPidFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createPidFileFailed",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "truncateFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 11,
        "ccnMethodMax": 3,
        "externals": [
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "DanchukAS\\DenyMultiplyRun\\Exception\\LockFileFail",
            "self",
            "self",
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "self",
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "DanchukAS\\DenyMultiplyRun\\Exception\\CloseFileFail",
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "DanchukAS\\DenyMultiplyRun\\Exception\\DeleteFileFail",
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "DanchukAS\\DenyMultiplyRun\\Exception\\OpenFileFail",
            "RuntimeException",
            "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
            "self",
            "DanchukAS\\DenyMultiplyRun\\Exception\\FileExisted",
            "RuntimeException",
            "RuntimeException"
        ],
        "lcom": 11,
        "length": 125,
        "vocabulary": 37,
        "volume": 651.18,
        "difficulty": 12.38,
        "effort": 8058.37,
        "level": 0.08,
        "bugs": 0.22,
        "time": 448,
        "intelligentContent": 52.62,
        "number_operators": 48,
        "number_operands": 77,
        "number_operators_unique": 9,
        "number_operands_unique": 28,
        "cloc": 93,
        "loc": 215,
        "lloc": 122,
        "mi": 75.88,
        "mIwoC": 33.31,
        "commentWeight": 42.58,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.03,
        "relativeSystemComplexity": 5.03,
        "totalStructuralComplexity": 44,
        "totalDataComplexity": 11.33,
        "totalSystemComplexity": 55.33,
        "pageRank": 0.1,
        "afferentCoupling": 7,
        "efferentCoupling": 18,
        "instability": 0.72,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\ErrorHandler",
        "interface": false,
        "methods": [
            {
                "name": "startErrorHandle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "errorHandle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LogicException"
        ],
        "lcom": 2,
        "length": 21,
        "vocabulary": 14,
        "volume": 79.95,
        "difficulty": 1.42,
        "effort": 113.27,
        "level": 0.71,
        "bugs": 0.03,
        "time": 6,
        "intelligentContent": 56.44,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 21,
        "loc": 37,
        "lloc": 16,
        "mi": 106.26,
        "mIwoC": 60.28,
        "commentWeight": 45.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "pageRank": 0.18,
        "afferentCoupling": 6,
        "efferentCoupling": 1,
        "instability": 0.14,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\ReadFileFail",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\CloseFileFail",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\DeleteFileFail",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\PidBiggerMax",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\ConvertPidFail",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\ProcessExisted",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 2,
        "effort": 67.38,
        "level": 0.5,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 16.84,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\PidFileEmpty",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 9,
        "lloc": 4,
        "mi": 216.73,
        "mIwoC": 171,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\FileExisted",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\PidLessMin",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\OpenFileFail",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "LogicException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 9,
        "lloc": 4,
        "mi": 216.73,
        "mIwoC": 171,
        "commentWeight": 45.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "DanchukAS\\DenyMultiplyRun\\Exception\\LockFileFail",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException",
            "Throwable",
            "parent"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 0.92,
        "effort": 30.88,
        "level": 1.09,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.75,
        "number_operators": 1,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 16,
        "loc": 25,
        "lloc": 9,
        "mi": 115.63,
        "mIwoC": 68.35,
        "commentWeight": 47.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    }
]