tests:
    "Commands should be fast enough":
        command: ".*" # run the assertions for all CLI commands
        assertions:
            - "main.wall_time < 5ms" # wall clock time is less than 2s
            - "main.peak_memory < 1M" # memory does not exceed 10mb