checks:
    php: true
build:
    tests:
        override:
            - phpcs-run
            -
              command: phpunit --coverage-clover=build/logs/clover.xml
                  coverage:
                      file: build/logs/clover.xml
                      format: php-clover

    environment:
        php:
            version: 7.1