language: php
php:
  # min 7.0
  - '7.0'
  - '7.1'
  # for find out max version php
  - nightly

# next all for codecov.io
before_install:
  - sudo pip install codecov
after_success:
  - codecov

# next all for codacy.com
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n
script:
  - php vendor/bin/phpunit
after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  # next all for scrutinizer-ci.com
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml