language: php
php:
  - '7.0'
  - '7.1'
  - nightly

before_install:
  - sudo pip install codecov

after_success:
  - codecov

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml