<?php
declare(strict_types=1);
/**
 * ============================================
 * WARNING!
 * Class is auto generated by buildTypeEnum.php.
 * Don't edit it manually.
 * ============================================
 */

namespace DanchukAS\Mock;

/**
 * Class TypeEnum
 * @package DanchukAS\Mock
 */
class TypeEnum
{
    // available types
    {PROPERTY}
}
