<?php
declare(strict_types=1);
/**
 * ============================================
 * WARNING!
 * Class is auto generated by buildTypeEnum.php.
 * Don't edit it manually.
 * ============================================
 */

namespace DanchukAS\Mock;

/**
 * Class TypeEnum
 * @package DanchukAS\Mock
 */
class TypeEnum
{
    // available types
    const ARRAY = 'array';
    const BOOLEAN = 'boolean';
    const DOUBLE = 'double';
    const INTEGER = 'integer';
    const /** @noinspection PhpConstantNamingConventionInspection */
        NULL = 'null';
    const OBJECT = 'object';
    const RESOURCE = 'resource';
    const STRING = 'string';
    const UNKNOWN = 'unknown';
}
