<?php
declare(strict_types=1);
/**
 * ============================================
 * WARNING!
 * Class is auto generated by buildTypeEnum.php.
 * Don't edit it manually.
 * ============================================
 */

namespace DanchukAS\Mock;

/**
 * Class TypeEnum
 * @package DanchukAS\Mock
 */
class TypeEnum
{
    // available types
    public const ARRAY = "array";
    public const BOOLEAN = "boolean";
    public const DOUBLE = "double";
    public const INTEGER = "integer";
    public const /** @noinspection PhpConstantNamingConventionInspection */
        NULL = "null";
    public const OBJECT = "object";
    public const RESOURCE = "resource";
    public const STRING = "string";
    public const UNKNOWN = "unknown";
}
